cellSet = {
    0: {
        "name": "0",
        "type": "I",
        "charging": 0
    },
    1: {
        "name": "1",
        "type": "I",
        "charging": 0
    },
    2: {
        "name": "2",
        "type": "I",
        "charging": 0
    },
    3: {
        "name": "3",
        "type": "I",
        "charging": 0
    },
    4: {
        "name": "4",
        "type": "I",
        "charging": 0
    },
    5: {
        "name": "5",
        "type": "I",
        "charging": 0
    },
    6: {
        "name": "6",
        "type": "I",
        "charging": 0
    },
    7: {
        "name": "7",
        "type": "I",
        "charging": 0
    },
    8: {
        "name": "8",
        "type": "I",
        "charging": 0
    },
    9: {
        "name": "9",
        "type": "I",
        "charging": 0
    },
    10: {
        "name": "10",
        "type": "I",
        "charging": 0
    },
    11: {
        "name": "11",
        "type": "I",
        "charging": 0
    },
    12: {
        "name": "12",
        "type": "I",
        "charging": 0
    },
    13: {
        "name": "R1",
        "type": "R",
        "charging": 0
    },
    14: {
        "name": "R2",
        "type": "R",
        "charging": 0
    },
    33: {
        "name": "S1",
        "type": "S",
        "charging": 0
    },
    34: {
        "name": "S2",
        "type": "S",
        "charging": 0
    },
    17: {
        "name": "C1",
        "type": "C",
        "charging": 2
    },
    18: {
        "name": "C2",
        "type": "C",
        "charging": 2,
    },
    19: {
        "name": "C3",
        "charging": 2,
        "type": "C"
    },
    20: {
        "name": "C4",
        "type": "C",
        "charging": 2
    },
    21: {
        "name": "C1",
        "type": "C",
        "charging": 1
    },
    22: {
        "name": "C1",
        "type": "C",
        "charging": 3
    },
    23: {
        "name": "C1",
        "type": "C",
        "charging": 4
    },
    24: {
        "name": "C2",
        "type": "C",
        "charging": 1
    },
    25: {
        "name": "C2",
        "type": "C",
        "charging": 3
    },
    26: {
        "name": "C2",
        "type": "C",
        "charging": 4
    },
    27: {
        "name": "C3",
        "type": "C",
        "charging": 1
    },
    28: {
        "name": "C3",
        "type": "C",
        "charging": 3
    },
    29: {
        "name": "C3",
        "type": "C",
        "charging": 4
    },
    30: {
        "name": "C4",
        "type": "C",
        "charging": 1
    },
    31: {
        "name": "C4",
        "type": "C",
        "charging": 3
    },
    32: {
        "name": "C4",
        "type": "C",
        "charging": 4
    },
    15: {
        "name": "C5",
        "type": "C",
        "charging": 5
    },
    16: {
        "name": "C6",
        "type": "C",
        "charging": 6
    }
}
arcSet = {
    (0, 1): {'back_speed': {},
             'free_speed': {},
             'len': 2700.0,
             'max_density': 0.1,
             'max_flow': {}},
    (0, 3): {'back_speed': {},
             'free_speed': {},
             'len': 2250.0,
             'max_density': 0.1,
             'max_flow': {}},
    (1, 4): {'back_speed': {},
             'free_speed': {},
             'len': 2250.0,
             'max_density': 0.1,
             'max_flow': {}},
    (1, 6): {'back_speed': {},
             'free_speed': {},
             'len': 4500.0,
             'max_density': 0.025,
             'max_flow': {}},
    (1, 17): {'back_speed': {},
              'free_speed': {},
              'len': 12000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (1, 21): {'back_speed': {},
              'free_speed': {},
              'len': 8000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (1, 22): {'back_speed': {},
              'free_speed': {},
              'len': 16000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (1, 23): {'back_speed': {},
              'free_speed': {},
              'len': 20000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (2, 3): {'back_speed': {},
             'free_speed': {},
             'len': 2700.0,
             'max_density': 0.1,
             'max_flow': {}},
    (2, 7): {'back_speed': {},
             'free_speed': {},
             'len': 3600.0,
             'max_density': 0.025,
             'max_flow': {}},
    (3, 4): {'back_speed': {},
             'free_speed': {},
             'len': 1800.0,
             'max_density': 0.05,
             'max_flow': {}},
    (3, 7): {'back_speed': {},
             'free_speed': {},
             'len': 2700.0,
             'max_density': 0.1,
             'max_flow': {}},
    (3, 19): {'back_speed': {},
              'free_speed': {},
              'len': 12000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (3, 27): {'back_speed': {},
              'free_speed': {},
              'len': 8000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (3, 28): {'back_speed': {},
              'free_speed': {},
              'len': 16000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (3, 29): {'back_speed': {},
              'free_speed': {},
              'len': 20000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (4, 5): {'back_speed': {},
             'free_speed': {},
             'len': 1800.0,
             'max_density': 0.1,
             'max_flow': {}},
    (4, 8): {'back_speed': {},
             'free_speed': {},
             'len': 4050.0,
             'max_density': 0.1,
             'max_flow': {}},
    (4, 20): {'back_speed': {},
              'free_speed': {},
              'len': 12000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (4, 30): {'back_speed': {},
              'free_speed': {},
              'len': 8000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (4, 31): {'back_speed': {},
              'free_speed': {},
              'len': 16000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (4, 32): {'back_speed': {},
              'free_speed': {},
              'len': 20000.0,
              'max_density': 0.001,
              'max_flow': {}},
    (5, 6): {'back_speed': {},
             'free_speed': {},
             'len': 1800.0,
             'max_density': 0.1,
             'max_flow': {}},
    (5, 9): {'back_speed': {},
             'free_speed': {},
             'len': 2700.0,
             'max_density': 0.1,
             'max_flow': {}},
    (6, 10): {'back_speed': {},
              'free_speed': {},
              'len': 2700.0,
              'max_density': 0.1,
              'max_flow': {}},
    (7, 8): {'back_speed': {},
             'free_speed': {},
             'len': 3150.0,
             'max_density': 0.1,
             'max_flow': {}},
    (7, 11): {'back_speed': {},
              'free_speed': {},
              'len': 2700.0,
              'max_density': 0.1,
              'max_flow': {}},
    (7, 18): {'back_speed': {},
              'free_speed': {},
              'len': 12000.0,
              'max_density': 0.01,
              'max_flow': {}},
    (7, 24): {'back_speed': {},
              'free_speed': {},
              'len': 8000.0,
              'max_density': 0.01,
              'max_flow': {}},
    (7, 25): {'back_speed': {},
              'free_speed': {},
              'len': 16000.0,
              'max_density': 0.01,
              'max_flow': {}},
    (7, 26): {'back_speed': {},
              'free_speed': {},
              'len': 20000.0,
              'max_density': 0.01,
              'max_flow': {}},
    (8, 9): {'back_speed': {},
             'free_speed': {},
             'len': 1800.0,
             'max_density': 0.025,
             'max_flow': {}},
    (9, 10): {'back_speed': {},
              'free_speed': {},
              'len': 2700.0,
              'max_density': 0.1,
              'max_flow': {}},
    (9, 12): {'back_speed': {},
              'free_speed': {},
              'len': 2700.0,
              'max_density': 0.1,
              'max_flow': {}},
    (10, 15): {'back_speed': {},
               'free_speed': {},
               'len': 0.0,
               'max_density': 0.1,
               'max_flow': {}},
 (10, 33): {'back_speed': {},
            'free_speed': {},
            'len': 0.0,
            'max_density': 0.1,
            'max_flow': {}},
 (12, 34): {'back_speed': {},
            'free_speed': {},
            'len': 0.0,
            'max_density': 0.1,
            'max_flow': {}},
    (11, 12): {'back_speed': {},
               'free_speed': {},
               'len': 3600.0,
               'max_density': 0.1,
               'max_flow': {}},
    (12, 16): {'back_speed': {},
               'free_speed': {},
               'len': 0.0,
               'max_density': 0.1,
               'max_flow': {}},
    (13, 0): {'back_speed': {},
              'free_speed': {},
              'len': 0.0,
              'max_density': 0.1,
              'max_flow': {}},
    (14, 2): {'back_speed': {},
              'free_speed': {},
              'len': 0.0,
              'max_density': 0.1,
              'max_flow': {}},
(15, 33): {'back_speed': {},
               'free_speed': {},
               'len': 0.0,
               'max_density': 0.1,
               'max_flow': {}},
(16, 34): {'back_speed': {},
               'free_speed': {},
               'len': 0.0,
               'max_density': 0.1,
               'max_flow': {}},
    (17, 6): {'back_speed': {},
              'free_speed': {},
              'len': 4500.0,
              'max_density': 0.1,
              'max_flow': {}},
    (18, 11): {'back_speed': {},
               'free_speed': {},
               'len': 2700.0,
               'max_density': 0.1,
               'max_flow': {}},
    (19, 8): {'back_speed': {},
              'free_speed': {},
              'len': 5850.0,
              'max_density': 0.1,
              'max_flow': {}},
    (20, 9): {'back_speed': {},
              'free_speed': {},
              'len': 5175.0,
              'max_density': 0.1,
              'max_flow': {}},
    (21, 6): {'back_speed': {},
              'free_speed': {},
              'len': 4500.0,
              'max_density': 0.1,
              'max_flow': {}},
    (22, 6): {'back_speed': {},
              'free_speed': {},
              'len': 4500.0,
              'max_density': 0.1,
              'max_flow': {}},
    (23, 6): {'back_speed': {},
              'free_speed': {},
              'len': 4500.0,
              'max_density': 0.1,
              'max_flow': {}},
    (24, 11): {'back_speed': {},
               'free_speed': {},
               'len': 2700.0,
               'max_density': 0.1,
               'max_flow': {}},
    (25, 11): {'back_speed': {},
               'free_speed': {},
               'len': 2700.0,
               'max_density': 0.1,
               'max_flow': {}},
    (26, 11): {'back_speed': {},
               'free_speed': {},
               'len': 2700.0,
               'max_density': 0.1,
               'max_flow': {}},
    (27, 8): {'back_speed': {},
              'free_speed': {},
              'len': 5850.0,
              'max_density': 0.1,
              'max_flow': {}},
    (28, 8): {'back_speed': {},
              'free_speed': {},
              'len': 5850.0,
              'max_density': 0.1,
              'max_flow': {}},
    (29, 8): {'back_speed': {},
              'free_speed': {},
              'len': 5850.0,
              'max_density': 0.1,
              'max_flow': {}},
    (30, 9): {'back_speed': {},
              'free_speed': {},
              'len': 4500.0,
              'max_density': 0.1,
              'max_flow': {}},
    (31, 9): {'back_speed': {},
              'free_speed': {},
              'len': 4500.0,
              'max_density': 0.1,
              'max_flow': {}},
    (32, 9): {'back_speed': {},
              'free_speed': {},
              'len': 4500.0,
              'max_density': 0.1,
              'max_flow': {}}
}